name: mobile_chatgpt
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  envied: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  envied_generator: ^0.3.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
