name: mobile_chatgpt
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  envied: ^0.3.0
  flutter_svg: ^2.0.1
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  flutter_gen_runner: ^5.2.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
flutter_gen:
  assets:
    package_parameter_enabled: true
  output: lib/generated/
  line_length: 80

  integrations:
    flutter_svg: true
